//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public int PilotId { get; set; }
        public string Név { get; set; }
        public Nullable<int> Nem { get; set; }
        public Nullable<int> Kor { get; set; }
        public Nullable<int> C18f2 { get; set; }
        public Nullable<int> C19f2 { get; set; }
        public Nullable<int> C20f2 { get; set; }
        public Nullable<int> C18f3 { get; set; }
        public Nullable<int> C19f3 { get; set; }
        public Nullable<int> C20f3 { get; set; }
        public Nullable<int> C18g3 { get; set; }
        public Nullable<int> C18fe { get; set; }
        public Nullable<int> C19fe { get; set; }
        public Nullable<int> C20fe { get; set; }
        public Nullable<int> egyéb { get; set; }
        public Nullable<int> szerződés { get; set; }
        public Nullable<int> verseny { get; set; }
        public Nullable<int> teszt { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Place Place2 { get; set; }
        public virtual Place Place3 { get; set; }
        public virtual Place Place4 { get; set; }
        public virtual Place Place5 { get; set; }
        public virtual Place Place6 { get; set; }
        public virtual Place Place7 { get; set; }
        public virtual Place Place8 { get; set; }
        public virtual Place Place9 { get; set; }
    }
}
